Repository Software-Meister-High-School-Community/MOIZA-Spring-Server, pull requests merged in 2022-03, with the labels that each got.

#2 🔀 :: (#1) 프로젝트 생성
  .github/workflows/Init.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/moizaspringserver/MoizaSpringServerApplication.java
  src/main/resources/application.properties
  src/test/java/com/example/moizaspringserver/MoizaSpringServerApplicationTests.java
Labels: 프로젝트 설정

#7 🔀 :: (#6) BaseEntity 설정
  src/main/java/com/example/moizaspringserver/global/config/JpaConfig.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseIdEntity.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseTimeEntity.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseTimeIdEntity.java
Labels: 기능 추가

#11 🔀 :: (#9) basetimeEntity 추가
  src/main/java/com/example/moizaspringserver/global/config/JpaConfig.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseIdEntity.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseTimeEntity.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseTimeIdEntity.java
Labels: 기능 추가

#5 🔀 :: (#4) User 엔티티 생성
  .github/CODEOWNERS
  src/main/java/com/example/moizaspringserver/domain/user/domain/User.java
  src/main/java/com/example/moizaspringserver/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/moizaspringserver/domain/user/domain/type/School.java
  src/main/java/com/example/moizaspringserver/domain/user/domain/type/Sex.java
  src/main/java/com/example/moizaspringserver/global/enums/UserType.java
  src/main/java/com/example/moizaspringserver/infrastructure/s3/DefaultImage.java
  src/main/resources/application.yml
Labels: 기능 추가

#15 🔀 :: (#14) 팔로우 / 팔로워 엔티티 생성
  src/main/java/com/example/moizaspringserver/domain/follow/domain/entity/Follow.java
  src/main/java/com/example/moizaspringserver/domain/follow/domain/repository/FollowRepository.java
Labels: 기능 추가

#25 🔀 :: (#23) 알림 엔티티 생성
  src/main/java/com/example/moizaspringserver/domain/notification/domain/entity/NotificationList.java
  src/main/java/com/example/moizaspringserver/domain/notification/domain/entity/NotificationListId.java
  src/main/java/com/example/moizaspringserver/domain/notification/domain/repository/NotificationEntityRepository.java
  src/main/java/com/example/moizaspringserver/domain/notification/domain/repository/NotificationListRepository.java
Labels: 기능 추가

#13 🔀 :: (#12) feed 엔티티
  src/main/java/com/example/moizaspringserver/feed/entity/Feed.java
  src/main/java/com/example/moizaspringserver/feed/entity/FeedAttachmentFile.java
  src/main/java/com/example/moizaspringserver/feed/entity/LocalFeed.java
  src/main/java/com/example/moizaspringserver/feed/entity/PublicFeed.java
  src/main/java/com/example/moizaspringserver/feed/respository/FeedAttachmentFileRepository.java
  src/main/java/com/example/moizaspringserver/feed/respository/FeedRepository.java
  src/main/java/com/example/moizaspringserver/feed/respository/LocalFeedRepository.java
  src/main/java/com/example/moizaspringserver/feed/respository/PublicFeedRepository.java
  src/main/java/com/example/moizaspringserver/feed/type/FeedType.java
Labels: 리펙토링

#19 🔀 :: (#18) 공지사항 엔티티 생성
  src/main/java/com/example/moizaspringserver/domain/notice/entity/Notice.java
  src/main/java/com/example/moizaspringserver/domain/notice/repository/NoticeRepository.java
Labels: 기능 추가

#21 🔀 :: (#20) UserIntroduceLink 엔티티 생성
  src/main/java/com/example/moizaspringserver/domain/user/domain/type/Sex.java
  src/main/java/com/example/moizaspringserver/domain/user/entity/User.java
  src/main/java/com/example/moizaspringserver/domain/user/entity/UserIntroduceLink.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserIntroduceLinkRepository.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserRepository.java
  src/main/java/com/example/moizaspringserver/domain/user/type/School.java
  src/main/java/com/example/moizaspringserver/domain/user/type/Sex.java
Labels: 기능 추가

#27 🔀 :: (#22) 도메인 패키지 구조
  src/main/java/com/example/moizaspringserver/domain/feed/entity/Feed.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/FeedAttachmentFile.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/LocalFeed.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/PublicFeed.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedAttachmentFileRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/LocalFeedRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/PublicFeedRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/type/FeedType.java
  src/main/java/com/example/moizaspringserver/domain/follow/domain/repository/FollowRepository.java
  src/main/java/com/example/moizaspringserver/domain/follow/entity/Follow.java
  src/main/java/com/example/moizaspringserver/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/moizaspringserver/domain/notice/entity/Notice.java
  src/main/java/com/example/moizaspringserver/domain/notice/repository/NoticeRepository.java
  src/main/java/com/example/moizaspringserver/domain/notification/domain/repository/NotificationEntityRepository.java
  src/main/java/com/example/moizaspringserver/domain/notification/domain/repository/NotificationListRepository.java
  src/main/java/com/example/moizaspringserver/domain/notification/entity/NotificationEntity.java
  src/main/java/com/example/moizaspringserver/domain/notification/entity/NotificationList.java
  src/main/java/com/example/moizaspringserver/domain/notification/entity/NotificationListId.java
  src/main/java/com/example/moizaspringserver/domain/notification/repository/NotificationEntityRepository.java
  src/main/java/com/example/moizaspringserver/domain/notification/repository/NotificationListRepository.java
  src/main/java/com/example/moizaspringserver/domain/notification/type/Type.java
  src/main/java/com/example/moizaspringserver/domain/user/entity/User.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserIntroduceLinkRepository.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserRepository.java
  src/main/java/com/example/moizaspringserver/feed/respository/FeedAttachmentFileRepository.java
  src/main/java/com/example/moizaspringserver/feed/respository/FeedRepository.java
  src/main/java/com/example/moizaspringserver/feed/respository/LocalFeedRepository.java
  src/main/java/com/example/moizaspringserver/feed/respository/PublicFeedRepository.java
  src/main/java/com/example/moizaspringserver/feed/type/FeedType.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseIdEntity.java
  src/main/java/com/example/moizaspringserver/global/entity/BaseTimeIdEntity.java
Labels: 리펙토링

#36 🔀 :: (#29) 검색기록 엔티티
  src/main/java/com/example/moizaspringserver/domain/user/entity/SearchHistory.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/SearchHistoryRepository.java
Labels: 기능 추가

#34 🔀 :: (#30) 졸업생 인증파일 엔티티
  src/main/java/com/example/moizaspringserver/domain/user/entity/GraduateVerifyingFile.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/GraduateVerifyingFileRepository.java
Labels: 기능 추가

#33 🔀 :: (#32) 팔로우 엔티티 변경
  src/main/java/com/example/moizaspringserver/domain/follow/entity/Follow.java
  src/main/java/com/example/moizaspringserver/domain/follow/entity/FollowId.java
  src/main/java/com/example/moizaspringserver/domain/follow/repository/FollowRepository.java
Labels: 리펙토링

#39 🔀 :: (#24) 유저 정지 엔티티 생성
  src/main/java/com/example/moizaspringserver/domain/user/entity/UserSuspension.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserSuspensionRepository.java
Labels: 기능 추가

#38 🔀 :: (#28) 좋아요 엔티티
  src/main/java/com/example/moizaspringserver/domain/feed/entity/FeedLike.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/FeedLikeId.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedLikeRepository.java
Labels: 기능 추가

#35 🔀 :: (#31) 카테고리 관련 엔티티
  src/main/java/com/example/moizaspringserver/domain/feed/entity/Category.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/FeedCategory.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/FeedCategoryId.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/CategoryRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedCategoryRepository.java
Labels: 기능 추가

#41 🔀 :: (#40) DS_STORE gitignore
  .gitignore
Labels: 프로젝트 설정

#37 🔀 :: (#17) 댓글 엔티티
  src/main/java/com/example/moizaspringserver/domain/comment/entity/Comment.java
  src/main/java/com/example/moizaspringserver/domain/comment/repository/CommentRepository.java
Labels: 기능 추가

#44 🔀 :: (#43) Feed 엔티티
  src/main/java/com/example/moizaspringserver/domain/category/entity/Category.java
  src/main/java/com/example/moizaspringserver/domain/category/entity/FeedCategory.java
  src/main/java/com/example/moizaspringserver/domain/category/entity/FeedCategoryId.java
  src/main/java/com/example/moizaspringserver/domain/category/repository/CategoryRepository.java
  src/main/java/com/example/moizaspringserver/domain/category/repository/FeedCategoryRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/LocalFeed.java
  src/main/java/com/example/moizaspringserver/domain/feed/entity/PublicFeed.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedCategoryRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedLikeRepository.java
  src/main/java/com/example/moizaspringserver/domain/graduate/entity/GraduateVerifyingFile.java
  src/main/java/com/example/moizaspringserver/domain/graduate/repository/GraduateVerifyingFileRepository.java
  src/main/java/com/example/moizaspringserver/domain/like/entity/FeedLike.java
  src/main/java/com/example/moizaspringserver/domain/like/entity/FeedLikeId.java
  src/main/java/com/example/moizaspringserver/domain/like/repository/FeedLikeRepository.java
Labels: Chore

#47 🔀 :: (#45) ErrorHandler
  src/main/java/com/example/moizaspringserver/global/error/ErrorResponse.java
  src/main/java/com/example/moizaspringserver/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/moizaspringserver/global/error/exception/CustomException.java
  src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
Labels: 기능 추가

#46 🔀 :: (#26) 레디스 엔티티 들들들
  build.gradle
  src/main/java/com/example/moizaspringserver/domain/auth/entity/EmailCode.java
  src/main/java/com/example/moizaspringserver/domain/auth/entity/RefreshToken.java
  src/main/java/com/example/moizaspringserver/domain/auth/repository/EmailCodeRepository.java
  src/main/java/com/example/moizaspringserver/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/moizaspringserver/domain/auth/type/Type.java
  src/main/java/com/example/moizaspringserver/domain/viewcount/entity/FeedViewCount.java
  src/main/java/com/example/moizaspringserver/domain/viewcount/repository/FeedViewCountRepository.java
Labels: 기능 추가

#51 🔀 :: (#50) 신고 Entity들 상속문제 해결
  src/main/java/com/example/moizaspringserver/domain/report/entity/CommentReport.java
  src/main/java/com/example/moizaspringserver/domain/report/entity/FeedReport.java
  src/main/java/com/example/moizaspringserver/domain/report/entity/UserReport.java
Labels: 버그

#52 🔀 :: (#48) security 설정
  build.gradle
  src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: 기능 추가, 프로젝트 설정

#49 🔀 :: (#8) lint 및 ci setting
  .github/workflows/Build.yml
  build.gradle
  src/main/resources/application.yml
Labels: 기능 추가
