Repository Software-Meister-High-School-Community/MOIZA-Spring-Server, pull requests merged in 2022-05, with the labels that each got.

#64 🔀 :: (#63) 유저 로그인
  src/main/java/com/example/moizaspringserver/domain/auth/exception/PasswordMismatchException.java
  src/main/java/com/example/moizaspringserver/domain/auth/facade/AuthFacade.java
  src/main/java/com/example/moizaspringserver/domain/auth/presentation/AuthController.java
  src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/request/UserSignInRequest.java
  src/main/java/com/example/moizaspringserver/domain/auth/service/TokenRefreshService.java
  src/main/java/com/example/moizaspringserver/domain/auth/service/UserSignInService.java
  src/main/java/com/example/moizaspringserver/domain/user/entity/User.java
  src/main/java/com/example/moizaspringserver/domain/user/entity/UserDeviceToken.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserDeviceTokenRepository.java
  src/main/java/com/example/moizaspringserver/global/config/PropertiesConfig.java
  src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
  src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
  src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
  src/main/java/com/example/moizaspringserver/global/security/properties/JwtProperties.java
  src/main/resources/application.yml
Labels: 기능 추가

#66 🔀 :: (#65) 유저 회원가입
  src/main/java/com/example/moizaspringserver/domain/auth/entity/EmailCode.java
  src/main/java/com/example/moizaspringserver/domain/user/entity/User.java
  src/main/java/com/example/moizaspringserver/domain/user/exception/EmailCodeNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/user/exception/EmailCodeNotVerifiedException.java
  src/main/java/com/example/moizaspringserver/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/com/example/moizaspringserver/domain/user/presentation/UserController.java
  src/main/java/com/example/moizaspringserver/domain/user/presentation/dto/request/UserSingUpRequest.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserRepository.java
  src/main/java/com/example/moizaspringserver/domain/user/service/UserSingUpService.java
  src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
  src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
Labels: 기능 추가

#81 🔀 :: (#80) 로그인 에러 해결
  src/main/java/com/example/moizaspringserver/domain/auth/presentation/dto/request/UserSignInRequest.java
  src/main/java/com/example/moizaspringserver/domain/auth/service/UserSignInService.java
Labels: 리펙토링, 버그

#79 🔀 :: (#78) 복합키를 사용하는 엔티티 메소드 재정의
  src/main/java/com/example/moizaspringserver/domain/category/entity/FeedCategoryId.java
  src/main/java/com/example/moizaspringserver/domain/follow/entity/FollowId.java
  src/main/java/com/example/moizaspringserver/domain/like/entity/FeedLikeId.java
  src/main/java/com/example/moizaspringserver/domain/notification/entity/NotificationListId.java
  src/main/java/com/example/moizaspringserver/domain/report/entity/CommentReportId.java
  src/main/java/com/example/moizaspringserver/domain/report/entity/FeedReportId.java
  src/main/java/com/example/moizaspringserver/domain/report/entity/UserReportId.java
Labels: Chore

#71 🔀 :: (#70) 팔로잉 가져오기 API
  src/main/java/com/example/moizaspringserver/domain/follow/presentation/FollowController.java
  src/main/java/com/example/moizaspringserver/domain/follow/presentation/dto/response/FollowingInfo.java
  src/main/java/com/example/moizaspringserver/domain/follow/presentation/dto/response/GetAllFollowingResponse.java
  src/main/java/com/example/moizaspringserver/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/moizaspringserver/domain/follow/service/FollowService.java
Labels: 기능 추가

#88 🔀 :: (#84) 전체 유저 검색 API
  src/main/java/com/example/moizaspringserver/domain/user/presentation/UserController.java
  src/main/java/com/example/moizaspringserver/domain/user/presentation/dto/response/UserListResponse.java
  src/main/java/com/example/moizaspringserver/domain/user/presentation/dto/response/UserResponse.java
  src/main/java/com/example/moizaspringserver/domain/user/repository/UserRepository.java
  src/main/java/com/example/moizaspringserver/domain/user/service/SearchUserService.java
  src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
Labels: 기능 추가

#86 🔀 :: (#85) 팔로우 추가 API
  src/main/java/com/example/moizaspringserver/domain/follow/entity/Follow.java
  src/main/java/com/example/moizaspringserver/domain/follow/exception/FollowAlreadyExistsException.java
  src/main/java/com/example/moizaspringserver/domain/follow/presentation/FollowController.java
  src/main/java/com/example/moizaspringserver/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/moizaspringserver/domain/follow/service/FollowEstablishService.java
  src/main/java/com/example/moizaspringserver/domain/follow/service/FollowQueryService.java
  src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
  src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
Labels: 기능 추가

#94 🔀 :: (#93) yml 세팅
  src/main/resources/application.yml
Labels: 프로젝트 설정

#90 🔀 :: (#82) 공지사항 상세 보기 API
  src/main/java/com/example/moizaspringserver/domain/notice/entity/NoticeAttachmentFile.java
  src/main/java/com/example/moizaspringserver/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/notice/presentation/NoticeController.java
  src/main/java/com/example/moizaspringserver/domain/notice/presentation/dto/Response/NoticeDetailResponse.java
  src/main/java/com/example/moizaspringserver/domain/notice/repository/NoticeAttachmentFileRepository.java
  src/main/java/com/example/moizaspringserver/domain/notice/service/QueryNoticeDetailService.java
  src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
  src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
Labels: 기능 추가

#77 🔀 :: (#75) 게시글 삭제 API
  src/main/java/com/example/moizaspringserver/domain/category/exception/FeedCategoryNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/category/repository/FeedCategoryRepository.java
  src/main/java/com/example/moizaspringserver/domain/comment/entity/CommentAttachmentFile.java
  src/main/java/com/example/moizaspringserver/domain/comment/exception/CommentAttachmentFileNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/comment/facade/CommentFacade.java
  src/main/java/com/example/moizaspringserver/domain/comment/repository/CommentAttachmentFileRepository.java
  src/main/java/com/example/moizaspringserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/exception/FeedAttachmentFileNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/feed/exception/FeedNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/feed/exception/LocalFeedNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/feed/exception/PublicFeedNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/feed/facade/FeedFacade.java
  src/main/java/com/example/moizaspringserver/domain/feed/presenstation/FeedController.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/FeedAttachmentFileRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/LocalFeedRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/respository/PublicFeedRepository.java
  src/main/java/com/example/moizaspringserver/domain/feed/service/DeleteFeedService.java
  src/main/java/com/example/moizaspringserver/domain/like/exception/FeedLikeNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/like/repository/FeedLikeRepository.java
  src/main/java/com/example/moizaspringserver/domain/report/exception/FeedReportNotFoundException.java
  src/main/java/com/example/moizaspringserver/domain/report/repository/FeedReportRepository.java
  src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
  src/main/java/com/example/moizaspringserver/global/error/security/CredentialsNotFoundException.java
  src/main/java/com/example/moizaspringserver/global/error/security/InvalidRoleException.java
  src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
Labels: 기능 추가
